spring.application.name=contas


# spring.datasource.url=jdbc:mysql://localhost:3306/contas
# spring.datasource.username=root
# spring.datasource.password=123456
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
#spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=false

spring.datasource.url=jdbc:sqlite:contas.sqlite
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update


spring.jpa.show-sql=true
